on:
  schedule:
    - cron: '0 14 * * *'  # should be 2pm UTC which is morning central time

jobs:
  check_temps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Temp every hour
        run: | 
          pip install requests
          python3 action_job.py "http://${{ secrets.IP_AND_PORT }}" ${{ secrets.IFTTT_EVENT }} ${{ secrets.IFTTT_TOKEN }}
